### ISSUE TITLE
Same star system rename problem

### ISSUE THREAD

**Issue by chinotauku** [endless-sky/endless-sky-editor#11]
When I rename on the same system, It's will pop-up a "the name has existed system" worming window sometimes.

**Comment by tehhowch** [comment]
Seems to be a general issue associated with name or government changes when you use the keyboard to confirm changes and then advance fields. If you use the mouse, there generally aren't these issues.

If I use Enter to "confirm" the name change, then Tab to switch to the government - that is generally when the "Duplicate name" error appears (and a very high chance of segfaulting in DetailView::NameChanged() or DetailView::GovernmentChanged(), due to inaccessible `system` properties.

**Comment by tehhowch** [comment]
I believe this is fixed with #17
